### PR TITLE
edit README after docker being mandatory

### PR DESCRIPTION
**Pull request by ziwot**
Hello here is  a small edition after docker now mandatory (see https://github.com/ligolang/dao-cameligo/commit/f9fd1374f2e80af6cb519ccad22721ad8f8beaae)

### CODE REVIEW

**Comment by ziwot** [comment]
@melwyn95 @Laucans

**Comment by melwyn95** [comment]
@Laucans can you have a look?

**Comment by Laucans** [comment]
Hello @der-alter, 

Starting by thanks for your feedback. 

Docker still not mandatory you can use make and override the ligo compiler using following command : 
`make compile ligo_compiler=<LIGO_COMPILER_COMMAND_OR_PATH>`

It's also available for protocol or project-root. 

But you got a point documentation is not correct and I gonna fix it on every templates than we provide.

**Comment by ziwot** [comment]
Hi! of course, but then `=` must be replaced by `?=`

uniformisation of variable names seems required too `PROTOCOL_OPT` is capitalized

I close this MR, let you find the `standard` way !

**Pull request closed without merging**
